[[prrte]]
arch = "aarch64"
git-tree-sha1 = "39427793113400987df363e5ba15ba6459c3285b"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "2fc3d56f7638c506918077efdf89bfbb61341d599d10f1cb0520a8f37c83fa09"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.aarch64-linux-gnu.tar.gz"
[[prrte]]
arch = "aarch64"
git-tree-sha1 = "c1e706106943e94fe9c3dfb6447961792e3ca752"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "f40bb928ef7adf79a2dae9750f4ddc51ec2e2d117e46dac745bf686326f413d5"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.aarch64-linux-musl.tar.gz"
[[prrte]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4af242330e56f67fb9af228b0fa0428cbce416dd"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "89dc8c6271d8e5a1ed8212b122b152f6334b3b98e7010d8b414b5978163e44df"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[prrte]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4bedd438646a58272127954db9e58ebe93b26ff"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "0e694c6f8cb07a83b5e2a135d582abe4fbea7d58e6bfb56b0b2c6f61cd2fae5b"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[prrte]]
arch = "i686"
git-tree-sha1 = "d27efddd0e98e352de470885baa913925236677a"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "705036331a3a44c2330d4144d24f2b217fda050a8e234ba8c1b4dcbb553468fb"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.i686-linux-gnu.tar.gz"
[[prrte]]
arch = "i686"
git-tree-sha1 = "44db293045f11871ce6a388e43856e7635225b25"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "0e0d9b4a0f55502e481cd11646140b89fdd4fd7eb71a27ccf76164ec86d365ae"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.i686-linux-musl.tar.gz"
[[prrte]]
arch = "powerpc64le"
git-tree-sha1 = "034bdd54b88d1ce7a76146ccb8e198808e080569"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "c8dde449f5572e41d1cdb6b1e7408ca850854c0ca41dc92bfe653dbb5a0c7f32"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "acf376594dd2f292afc723262d2e1c7594bea072"
os = "macos"

    [[prrte.download]]
    sha256 = "bf5d28f116ef25d636c42f337dc4fdfe0c22d32a672ae4b74ee68e80237a7914"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.x86_64-apple-darwin.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "9650245c97ffac3fa796811c98523986fb8b0ae7"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "67a73fa4c23ee4e7d2182e53ac4d43d11e2ca3889cc312091b9000cbaa706324"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.x86_64-linux-gnu.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "dda2c427fa47d2b7cfdbf08da3a26eabc534a0ee"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "807ae2b4f4985c09b2c8c28365793088713bf3cb0211220249386e75bb92de84"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+1/prrte.v2.0.0.x86_64-linux-musl.tar.gz"
