[[prrte]]
arch = "aarch64"
git-tree-sha1 = "8f93a080736e27c619ca38cff74de69ccc2f878f"
os = "macos"

    [[prrte.download]]
    sha256 = "844b0f3c8e9bc57e82fec6adc894e9b4c4ada852c4ba4a465b0b5b7703d037e9"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.aarch64-apple-darwin.tar.gz"
[[prrte]]
arch = "aarch64"
git-tree-sha1 = "79e35efcb2f5a485049751485cc5cbfc1df3980c"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "d8890e091e246d216f01c09de00ab151bece026f1e0c9fb2f80d3c491fd3b216"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.aarch64-linux-gnu.tar.gz"
[[prrte]]
arch = "aarch64"
git-tree-sha1 = "baaedefd97775c8be11980c495abe37caf4a0aa0"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "8e90834973bb8efd208c46ae3d8f8cb5f3675d8859554bd245dcdae520e40f62"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.aarch64-linux-musl.tar.gz"
[[prrte]]
arch = "aarch64"
git-tree-sha1 = "dbb3fc23f67c47b0b246f7a398c105e2bb6b41f3"
os = "freebsd"

    [[prrte.download]]
    sha256 = "527f1c4d6ee4565c7fce28b338118c2efdc641dd53f466d93d293bcda9165da7"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.aarch64-unknown-freebsd.tar.gz"
[[prrte]]
arch = "powerpc64le"
git-tree-sha1 = "a7d1c86377287fe7339380a031576611565e853d"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "753aa5150d5510da1a17836bdbbd3f7913bceb3115e50fb3a0140d39ac7ac8e0"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[prrte]]
arch = "riscv64"
git-tree-sha1 = "632ed6ccf6f7f82f9d6bf960f7572037d9ec74e4"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "877ca0ca60d8884c1c993d4ee87e3330f531eaab6f362732076e398b5de62ed1"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.riscv64-linux-gnu.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "2a0f43e27cdf46c2365c408e57f1a7f9e4facb4c"
os = "macos"

    [[prrte.download]]
    sha256 = "226536ea8c3c763b7211ecf0ecfc488d6f6004651d1b73f0b952219759653ea2"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.x86_64-apple-darwin.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "6dad6b0b0eed167ec9148e0bd0a65380452d6db9"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "048d4e68bbd824a60e277b61382d1b7a3b26e01a19048dc066e262ce957936b1"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.x86_64-linux-gnu.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "2c2d669918446c9c33c0de263490440b360a0d84"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "5ed5528e8ea17b7d75f03bb574d55e5ae9dc03150e11d1de7b41365951fde5c8"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.x86_64-linux-musl.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "9c4606179b0db400cc919d338ddfc7797e410174"
os = "freebsd"

    [[prrte.download]]
    sha256 = "4d9d7f0a7d78ea548eb4f6a7e49e231272d61f89893b458ff8701adbdfd36e4a"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v4.1.0+0/prrte.v4.1.0.x86_64-unknown-freebsd.tar.gz"
