[[prrte]]
arch = "aarch64"
git-tree-sha1 = "e294e9a77321af2d48c3c1ff075385e24fa03290"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "b05604852a68b8e92957b01804d98227ab5bdb354cf190ec0b5b5c1daf938ae2"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.aarch64-linux-gnu.tar.gz"
[[prrte]]
arch = "aarch64"
git-tree-sha1 = "c289df73885740a084242f8026ce80aaab66ec5d"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "8563377fff3f40b741f69e165cda58c8b6491af5d969c89e98a87fbcf96e2308"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.aarch64-linux-musl.tar.gz"
[[prrte]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e21027f5b82bc5a01468d592f6c08440484c4afe"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "e8fe40c3364026e3931ca2434e2c924be5254b6663117b8003ea079a817e2d39"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.armv7l-linux-gnueabihf.tar.gz"
[[prrte]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd41165a5b1ace03f3e36e374fd68c1e4c28d391"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "ebc14e05303bbeb336f96b3af396d71d0c988f5367df1284be40a3adf58599e9"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.armv7l-linux-musleabihf.tar.gz"
[[prrte]]
arch = "i686"
git-tree-sha1 = "56eb5d62d8b5f543b6d19286a23688dbe67af238"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "c85c0218437b3e0086a7f2a7c22da16bdf24f3a9acf1b0a289252969318015c1"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.i686-linux-gnu.tar.gz"
[[prrte]]
arch = "i686"
git-tree-sha1 = "93558b2b8624abce121506e07663a9a09e69ebb9"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "3c41656a1de88b0d5a9abc6042e7b6a9b70a7c355b675a7fba4deb120d21a937"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.i686-linux-musl.tar.gz"
[[prrte]]
arch = "powerpc64le"
git-tree-sha1 = "8e79790e802d5e427df0e9cd468199ca56c5f568"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "b95e0cd81c5ffa060a4eb9bb49bdf931d119c26807285035b467e2f2dd20ba13"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.powerpc64le-linux-gnu.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "b5c5f540fb9337d78be5ed55bd37981aac0ef76e"
os = "macos"

    [[prrte.download]]
    sha256 = "adb1adcde25073c18ae2cbed36f08e7ef1d97eb0fb9a6a41ffc187920561ca6f"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.x86_64-apple-darwin.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "0398a9c4c815e736983d734949b7291aaf9d11b5"
libc = "glibc"
os = "linux"

    [[prrte.download]]
    sha256 = "6ef6fc87bfdba8fb240fc175e6dbe39d99015cf9dd7726d8b07e2a66fca3617f"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.x86_64-linux-gnu.tar.gz"
[[prrte]]
arch = "x86_64"
git-tree-sha1 = "e5cbf6a81ae779d28b5ef817cd5eed01b7376cd0"
libc = "musl"
os = "linux"

    [[prrte.download]]
    sha256 = "da46d942c051c38360f8463839de097b14c3e82015c8a71dcf60380dd9677d89"
    url = "https://github.com/JuliaBinaryWrappers/prrte_jll.jl/releases/download/prrte-v2.0.0+2/prrte.v2.0.0.x86_64-linux-musl.tar.gz"
